export { default as appReducer } from './appReducer'
export { default as authReducer } from './authReducer'
export { default as dialogsReducer } from './dialogsReducer'
export { default as headerReducer } from './headerReducer'
export { default as profileReducer } from './profileReducer'
export { default as usersReducer } from './usersReducer'